// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI2cq19Ae2VNNgbr7yYpXcr-phvT7dYpc',
    appId: '1:38032763411:web:cf647c870d21818dc16de6',
    messagingSenderId: '38032763411',
    projectId: 'flexpos-pemob',
    authDomain: 'flexpos-pemob.firebaseapp.com',
    storageBucket: 'flexpos-pemob.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADTDo5skLAgKO7RscCrPi98MGU-J5XCdI',
    appId: '1:38032763411:android:dbca9fd7efea2e23c16de6',
    messagingSenderId: '38032763411',
    projectId: 'flexpos-pemob',
    storageBucket: 'flexpos-pemob.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWlLyQ77BXABM8aKkKbSM7I9wQPUmFvaU',
    appId: '1:38032763411:ios:fec4c4c53344a2ddc16de6',
    messagingSenderId: '38032763411',
    projectId: 'flexpos-pemob',
    storageBucket: 'flexpos-pemob.firebasestorage.app',
    iosBundleId: 'com.example.posKasir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWlLyQ77BXABM8aKkKbSM7I9wQPUmFvaU',
    appId: '1:38032763411:ios:fec4c4c53344a2ddc16de6',
    messagingSenderId: '38032763411',
    projectId: 'flexpos-pemob',
    storageBucket: 'flexpos-pemob.firebasestorage.app',
    iosBundleId: 'com.example.posKasir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI2cq19Ae2VNNgbr7yYpXcr-phvT7dYpc',
    appId: '1:38032763411:web:1ce25c837533bcb4c16de6',
    messagingSenderId: '38032763411',
    projectId: 'flexpos-pemob',
    authDomain: 'flexpos-pemob.firebaseapp.com',
    storageBucket: 'flexpos-pemob.firebasestorage.app',
  );
}
